global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "kv-raft-cluster"
    static_configs:
      - targets:
          - "kv-node1:9090"
          - "kv-node2:9090"
          - "kv-node3:9090"
        labels:
          cluster: "kv-raft"